# Generated by Django 3.2.19 on 2023-11-23 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_charges',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
