version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    networks:
      - foodie_network

networks:
  foodie_network:
    driver: bridge
